#!/bin/sh

SET_DESKTOP=$(readlink -f $HOME/.config/openbox/set-desktop)
if [ "$SET_DESKTOP" != "$HOME/.config/openbox/pcman" ]; then
# Pre-load menu
xdotool mousemove 0 0
xdotool key ctrl+alt+space
xdotool mousemove 300 300
openbox --reconfigure
fi
compton &

# Provides the desktop of choice, e.g. tint2 left icon panel or rox pinboard
# Can be selected from Menu > Desktop Manager
. $HOME/.config/openbox/set-desktop
sleep 2

chpupsocket $USER:$USER &
start-pulseaudio-x11 &

#parcellite &
sleep 1

#frisbee-tray &
#wicd-gtk --tray &

#volumeicon &

desktop_drive_icons &
sleep 6
if [ -f /mnt/live/tmp/modules ]; then
conky -c ~/.conkyrc-port &
else
conky -c ~/.conkyrc-live &
fi
#alsamixertray &